export { loginPage } from "./login";
export { scanPage } from "./scan";
export { newJobPage, jobDetailPage, progressPage } from "./jobs";
export { jobsManagerPage } from "./jobs-manager";
export { qrPage } from "./qr";
export { dashboardPage } from "./dashboard";
export { stationViewPage } from "./stations";
export { stagingPage } from "./staging";
export { kpiPage, taktPage } from "./kpi";
export { adminPage } from "./admin";
export { workbenchPage, myWorkbenchPage } from "./workbench";
export { fixitPage } from "./fixit";
export { stationMenuPage } from "./station-menu";
export { profilePage } from "./profile";
export { cabinetDetailPage } from "./cabinet-detail";
export { reportsPage } from "./reports";
export { monitorPage } from "./monitor";
