-- cab1.fabworks.app — HighCraft assembly-floor demo (generated by scripts/gen_seed_cab1.js)
-- 4 jobs: 6789 finished, 7012 almost done, 7045 ~10% in, 7060 pending/new.
-- Idempotent: wipes demo rows then reinserts with explicit ids.

DELETE FROM pause_events;
DELETE FROM fixit_requests;
DELETE FROM scans;
DELETE FROM build_sessions;
DELETE FROM sessions;
DELETE FROM cabinets;
DELETE FROM buckets;
DELETE FROM jobs;
DELETE FROM users WHERE email LIKE '%@highcraft.demo';

INSERT INTO users (id, name, email, pin, role) VALUES (1, 'Brad', 'brad@highcraft.demo', '917d94ab39ba1be10554a5a90fda41846b9c53f7a7c6d9c80c7ab92ed60776cd', 'admin');  -- PIN 1234
INSERT INTO users (id, name, email, pin, role) VALUES (2, 'Sam', 'sam@highcraft.demo', 'f2a2670fb35aee525981d13bc643ba91917d38ea57d26cdd82ae01459fc73d2d', 'supervisor');  -- PIN 3333
INSERT INTO users (id, name, email, pin, role) VALUES (3, 'Carlos', 'carlos@highcraft.demo', 'a5edfea3302687ee6c7aa1e78205bc5998328a29c384882b3455d640ef63e1f8', 'lead');  -- PIN 4444
INSERT INTO users (id, name, email, pin, role) VALUES (4, 'Mateo', 'mateo@highcraft.demo', '04334c8afa7933c068f677fcdd243840ee6312adb4ab3dd219716ec9b0207754', 'user');  -- PIN 1111
INSERT INTO users (id, name, email, pin, role) VALUES (5, 'Jordan', 'jordan@highcraft.demo', '22636e3e8fea0e9c503f618cfeb70fb0b204845b4a915bc78eb2d851d5459184', 'user');  -- PIN 2222
INSERT INTO users (id, name, email, pin, role) VALUES (6, 'Diego', 'diego@highcraft.demo', '76cca743c537385186ffb0e1e3cd2301f9024f31cccfb08b9a006e3a49689548', 'user');  -- PIN 1212
INSERT INTO users (id, name, email, pin, role) VALUES (7, 'Tony', 'tony@highcraft.demo', 'd32d40afa79582a3812b2ed8494e38a6620baebcd4ed54d5bd2b9ecf0e9ec552', 'user');  -- PIN 1313
INSERT INTO users (id, name, email, pin, role) VALUES (8, 'Marcus', 'marcus@highcraft.demo', '530b05d9f22a40e73ad0b30cb749260f687559345ec257a884c6d79ac58652a9', 'user');  -- PIN 1414
INSERT INTO users (id, name, email, pin, role) VALUES (9, 'Luis', 'luis@highcraft.demo', '6f6949ce36a3855a0cee2bb3470baebf05d07b57b0498ff865716f1b690154b7', 'user');  -- PIN 1515
INSERT INTO users (id, name, email, pin, role) VALUES (10, 'Priya', 'priya@highcraft.demo', 'b93491743be3af0cc972c1fceb40d37d23e88c1a1bdb503de34c22e411bab1e8', 'user');  -- PIN 1616
INSERT INTO users (id, name, email, pin, role) VALUES (11, 'Hector', 'hector@highcraft.demo', '2e8e508fdcf225ded99217121570d8ef02883601d1a3ea99e66ee9a7449ac8d8', 'user');  -- PIN 1717

INSERT INTO jobs (id, job_number, job_name, cabinet_count, status) VALUES (1, '6789', 'Somewhere House', 24, 'complete');
INSERT INTO jobs (id, job_number, job_name, cabinet_count, status) VALUES (2, '7012', 'Lakeside Remodel', 20, 'active');
INSERT INTO jobs (id, job_number, job_name, cabinet_count, status) VALUES (3, '7045', 'Maple Ave Kitchen', 20, 'active');
INSERT INTO jobs (id, job_number, job_name, cabinet_count, status) VALUES (4, '7060', 'Downtown Office Casework', 16, 'active');

-- buckets
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (1, 1, 'Nest 1', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (2, 1, 'Nest 2', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (3, 1, 'Nest 3', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (4, 1, 'Nest 4', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (5, 1, 'Nest 5', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (6, 1, 'Nest 6', 4, 'complete');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (7, 2, 'Nest 1', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (8, 2, 'Nest 2', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (9, 2, 'Nest 3', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (10, 2, 'Nest 4', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (11, 2, 'Nest 5', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (12, 3, 'Nest 1', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (13, 3, 'Nest 2', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (14, 3, 'Nest 3', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (15, 3, 'Nest 4', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (16, 3, 'Nest 5', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (17, 4, 'Nest 1', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (18, 4, 'Nest 2', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (19, 4, 'Nest 3', 4, 'pending');
INSERT INTO buckets (id, job_id, name, cabinet_count, status) VALUES (20, 4, 'Nest 4', 4, 'pending');

-- cabinets
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (1, 1, 1, 1, 'Base 36" Sink', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (2, 1, 1, 2, 'Base 24" 3-Drawer', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (3, 1, 1, 3, 'Base 18" Door', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (4, 1, 1, 4, 'Base 30" Door', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (5, 1, 2, 5, 'Base 15" Drawer', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (6, 1, 2, 6, 'Base 33" Corner', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (7, 1, 2, 7, 'Base 12" Filler', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (8, 1, 2, 8, 'Base 42" Lazy Susan', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (9, 1, 3, 9, 'Wall 30x36 Double', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (10, 1, 3, 10, 'Wall 24x36 Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (11, 1, 3, 11, 'Wall 30x18 Over-Range', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (12, 1, 3, 12, 'Wall 12x36 Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (13, 1, 4, 13, 'Wall 36x15 Bridge', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (14, 1, 4, 14, 'Wall 24x30 Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (15, 1, 4, 15, 'Wall 18x42 Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (16, 1, 4, 16, 'Wall 33x36 Double', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (17, 1, 5, 17, 'Tall 24x84 Pantry', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (18, 1, 5, 18, 'Tall 18x84 Broom', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (19, 1, 5, 19, 'Tall 30x90 Oven', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (20, 1, 5, 20, 'Tall 24x96 Pantry', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (21, 1, 6, 21, 'Vanity 48" Double', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (22, 1, 6, 22, 'Vanity 30" Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (23, 1, 6, 23, 'Vanity 36" Single', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (24, 1, 6, 24, 'Vanity 60" Double', 'staged', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (25, 2, 7, 25, 'Base 36" Sink', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (26, 2, 7, 26, 'Base 24" 3-Drawer', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (27, 2, 7, 27, 'Base 18" Door', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (28, 2, 7, 28, 'Base 30" Door', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (29, 2, 8, 29, 'Base 15" Drawer', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (30, 2, 8, 30, 'Base 33" Corner', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (31, 2, 8, 31, 'Base 12" Filler', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (32, 2, 8, 32, 'Base 42" Lazy Susan', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (33, 2, 9, 33, 'Wall 30x36 Double', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (34, 2, 9, 34, 'Wall 24x36 Single', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (35, 2, 9, 35, 'Wall 30x18 Over-Range', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (36, 2, 9, 36, 'Wall 12x36 Single', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (37, 2, 10, 37, 'Wall 36x15 Bridge', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (38, 2, 10, 38, 'Wall 24x30 Single', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (39, 2, 10, 39, 'Wall 18x42 Single', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (40, 2, 10, 40, 'Wall 33x36 Double', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (41, 2, 11, 41, 'Tall 24x84 Pantry', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (42, 2, 11, 42, 'Tall 18x84 Broom', 'assembling', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (43, 2, 11, 43, 'Tall 30x90 Oven', 'assembling', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (44, 2, 11, 44, 'Tall 24x96 Pantry', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (45, 3, 12, 45, 'Vanity 48" Double', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (46, 3, 12, 46, 'Vanity 30" Single', 'assembled', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (47, 3, 12, 47, 'Vanity 36" Single', 'assembling', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (48, 3, 12, 48, 'Vanity 60" Double', 'assembling', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (49, 3, 13, 49, 'Base 36" Sink', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (50, 3, 13, 50, 'Base 24" 3-Drawer', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (51, 3, 13, 51, 'Base 18" Door', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (52, 3, 13, 52, 'Base 30" Door', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (53, 3, 14, 53, 'Base 15" Drawer', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (54, 3, 14, 54, 'Base 33" Corner', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (55, 3, 14, 55, 'Base 12" Filler', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (56, 3, 14, 56, 'Base 42" Lazy Susan', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (57, 3, 15, 57, 'Wall 30x36 Double', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (58, 3, 15, 58, 'Wall 24x36 Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (59, 3, 15, 59, 'Wall 30x18 Over-Range', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (60, 3, 15, 60, 'Wall 12x36 Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (61, 3, 16, 61, 'Wall 36x15 Bridge', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (62, 3, 16, 62, 'Wall 24x30 Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (63, 3, 16, 63, 'Wall 18x42 Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (64, 3, 16, 64, 'Wall 33x36 Double', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (65, 4, 17, 65, 'Tall 24x84 Pantry', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (66, 4, 17, 66, 'Tall 18x84 Broom', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (67, 4, 17, 67, 'Tall 30x90 Oven', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (68, 4, 17, 68, 'Tall 24x96 Pantry', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (69, 4, 18, 69, 'Vanity 48" Double', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (70, 4, 18, 70, 'Vanity 30" Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (71, 4, 18, 71, 'Vanity 36" Single', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (72, 4, 18, 72, 'Vanity 60" Double', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (73, 4, 19, 73, 'Base 36" Sink', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (74, 4, 19, 74, 'Base 24" 3-Drawer', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (75, 4, 19, 75, 'Base 18" Door', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (76, 4, 19, 76, 'Base 30" Door', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (77, 4, 20, 77, 'Base 15" Drawer', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (78, 4, 20, 78, 'Base 33" Corner', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (79, 4, 20, 79, 'Base 12" Filler', 'pending', '[]');
INSERT INTO cabinets (id, job_id, bucket_id, cabinet_number, label, status, flags) VALUES (80, 4, 20, 80, 'Base 42" Lazy Susan', 'pending', '[]');

-- build sessions
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (1, 1, 1, 4, datetime('now','-242 minutes'), NULL, datetime('now','-216 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (2, 2, 1, 5, datetime('now','-1790 minutes'), NULL, datetime('now','-1762 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (3, 3, 1, 6, datetime('now','-587 minutes'), NULL, datetime('now','-563 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (4, 4, 1, 7, datetime('now','-681 minutes'), NULL, datetime('now','-651 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (5, 5, 1, 8, datetime('now','-957 minutes'), NULL, datetime('now','-928 minutes'), 480);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (6, 6, 1, 9, datetime('now','-4098 minutes'), NULL, datetime('now','-4063 minutes'), 720);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (7, 7, 1, 10, datetime('now','-4167 minutes'), NULL, datetime('now','-4137 minutes'), 240);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (8, 8, 1, 11, datetime('now','-1575 minutes'), NULL, datetime('now','-1548 minutes'), 420);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (9, 9, 1, 4, datetime('now','-1583 minutes'), NULL, datetime('now','-1560 minutes'), 60);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (10, 10, 1, 5, datetime('now','-1706 minutes'), NULL, datetime('now','-1679 minutes'), 300);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (11, 11, 1, 6, datetime('now','-1748 minutes'), NULL, datetime('now','-1720 minutes'), 60);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (12, 12, 1, 7, datetime('now','-3342 minutes'), NULL, datetime('now','-3315 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (13, 13, 1, 8, datetime('now','-2419 minutes'), NULL, datetime('now','-2382 minutes'), 720);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (14, 14, 1, 9, datetime('now','-1503 minutes'), NULL, datetime('now','-1483 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (15, 15, 1, 10, datetime('now','-3142 minutes'), NULL, datetime('now','-3105 minutes'), 420);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (16, 16, 1, 11, datetime('now','-4328 minutes'), NULL, datetime('now','-4293 minutes'), 480);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (17, 17, 1, 4, datetime('now','-2245 minutes'), NULL, datetime('now','-2227 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (18, 18, 1, 5, datetime('now','-1149 minutes'), NULL, datetime('now','-1129 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (19, 19, 1, 6, datetime('now','-1964 minutes'), NULL, datetime('now','-1935 minutes'), 180);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (20, 20, 1, 7, datetime('now','-3858 minutes'), NULL, datetime('now','-3838 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (21, 21, 1, 8, datetime('now','-4176 minutes'), NULL, datetime('now','-4144 minutes'), 420);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (22, 22, 1, 9, datetime('now','-3802 minutes'), NULL, datetime('now','-3782 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (23, 23, 1, 10, datetime('now','-2439 minutes'), NULL, datetime('now','-2405 minutes'), 540);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (24, 24, 1, 11, datetime('now','-463 minutes'), NULL, datetime('now','-437 minutes'), 180);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (25, 25, 2, 4, datetime('now','-423 minutes'), NULL, datetime('now','-395 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (26, 26, 2, 5, datetime('now','-183 minutes'), NULL, datetime('now','-160 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (27, 27, 2, 6, datetime('now','-479 minutes'), NULL, datetime('now','-439 minutes'), 660);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (28, 28, 2, 7, datetime('now','-475 minutes'), NULL, datetime('now','-442 minutes'), 720);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (29, 29, 2, 8, datetime('now','-455 minutes'), NULL, datetime('now','-414 minutes'), 720);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (30, 30, 2, 9, datetime('now','-370 minutes'), NULL, datetime('now','-346 minutes'), 240);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (31, 31, 2, 10, datetime('now','-142 minutes'), NULL, datetime('now','-112 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (32, 32, 2, 11, datetime('now','-261 minutes'), NULL, datetime('now','-230 minutes'), 60);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (33, 33, 2, 4, datetime('now','-75 minutes'), NULL, datetime('now','-38 minutes'), 480);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (34, 34, 2, 5, datetime('now','-124 minutes'), NULL, datetime('now','-94 minutes'), 120);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (35, 35, 2, 6, datetime('now','-1180 minutes'), NULL, datetime('now','-1158 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (36, 36, 2, 7, datetime('now','-1465 minutes'), NULL, datetime('now','-1441 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (37, 37, 2, 8, datetime('now','-1018 minutes'), NULL, datetime('now','-986 minutes'), 540);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (38, 38, 2, 9, datetime('now','-1671 minutes'), NULL, datetime('now','-1638 minutes'), 240);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (39, 39, 2, 10, datetime('now','-964 minutes'), NULL, datetime('now','-938 minutes'), 360);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (40, 40, 2, 11, datetime('now','-773 minutes'), NULL, datetime('now','-740 minutes'), 720);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (41, 41, 2, 4, datetime('now','-1827 minutes'), NULL, datetime('now','-1795 minutes'), 180);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (42, 42, 2, 5, datetime('now','-14 minutes'), datetime('now','-12 minutes'), NULL, 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (43, 43, 2, 6, datetime('now','-11 minutes'), NULL, NULL, 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (44, 45, 3, 7, datetime('now','-70 minutes'), NULL, datetime('now','-45 minutes'), 360);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (45, 46, 3, 8, datetime('now','-117 minutes'), NULL, datetime('now','-96 minutes'), 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (46, 47, 3, 9, datetime('now','-15 minutes'), NULL, NULL, 0);
INSERT INTO build_sessions (id, cabinet_id, job_id, user_id, started_at, paused_at, completed_at, total_paused_seconds) VALUES (47, 48, 3, 10, datetime('now','-37 minutes'), datetime('now','-29 minutes'), NULL, 0);

-- scans (to_assembly = ready, assembly_complete = done)
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (1, 1, 1, 1, 'assembly_complete', 'Mateo', datetime('now','-216 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (2, 1, 1, 2, 'assembly_complete', 'Jordan', datetime('now','-1762 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (3, 1, 1, 3, 'assembly_complete', 'Diego', datetime('now','-563 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (4, 1, 1, 4, 'assembly_complete', 'Tony', datetime('now','-651 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (5, 1, 2, 5, 'assembly_complete', 'Marcus', datetime('now','-928 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (6, 1, 2, 6, 'assembly_complete', 'Luis', datetime('now','-4063 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (7, 1, 2, 7, 'assembly_complete', 'Priya', datetime('now','-4137 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (8, 1, 2, 8, 'assembly_complete', 'Hector', datetime('now','-1548 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (9, 1, 3, 9, 'assembly_complete', 'Mateo', datetime('now','-1560 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (10, 1, 3, 10, 'assembly_complete', 'Jordan', datetime('now','-1679 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (11, 1, 3, 11, 'assembly_complete', 'Diego', datetime('now','-1720 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (12, 1, 3, 12, 'assembly_complete', 'Tony', datetime('now','-3315 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (13, 1, 4, 13, 'assembly_complete', 'Marcus', datetime('now','-2382 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (14, 1, 4, 14, 'assembly_complete', 'Luis', datetime('now','-1483 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (15, 1, 4, 15, 'assembly_complete', 'Priya', datetime('now','-3105 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (16, 1, 4, 16, 'assembly_complete', 'Hector', datetime('now','-4293 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (17, 1, 5, 17, 'assembly_complete', 'Mateo', datetime('now','-2227 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (18, 1, 5, 18, 'assembly_complete', 'Jordan', datetime('now','-1129 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (19, 1, 5, 19, 'assembly_complete', 'Diego', datetime('now','-1935 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (20, 1, 5, 20, 'assembly_complete', 'Tony', datetime('now','-3838 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (21, 1, 6, 21, 'assembly_complete', 'Marcus', datetime('now','-4144 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (22, 1, 6, 22, 'assembly_complete', 'Luis', datetime('now','-3782 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (23, 1, 6, 23, 'assembly_complete', 'Priya', datetime('now','-2405 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (24, 1, 6, 24, 'assembly_complete', 'Hector', datetime('now','-437 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (25, 2, 7, 25, 'assembly_complete', 'Mateo', datetime('now','-395 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (26, 2, 7, 26, 'assembly_complete', 'Jordan', datetime('now','-160 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (27, 2, 7, 27, 'assembly_complete', 'Diego', datetime('now','-439 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (28, 2, 7, 28, 'assembly_complete', 'Tony', datetime('now','-442 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (29, 2, 8, 29, 'assembly_complete', 'Marcus', datetime('now','-414 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (30, 2, 8, 30, 'assembly_complete', 'Luis', datetime('now','-346 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (31, 2, 8, 31, 'assembly_complete', 'Priya', datetime('now','-112 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (32, 2, 8, 32, 'assembly_complete', 'Hector', datetime('now','-230 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (33, 2, 9, 33, 'assembly_complete', 'Mateo', datetime('now','-38 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (34, 2, 9, 34, 'assembly_complete', 'Jordan', datetime('now','-94 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (35, 2, 9, 35, 'assembly_complete', 'Diego', datetime('now','-1158 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (36, 2, 9, 36, 'assembly_complete', 'Tony', datetime('now','-1441 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (37, 2, 10, 37, 'assembly_complete', 'Marcus', datetime('now','-986 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (38, 2, 10, 38, 'assembly_complete', 'Luis', datetime('now','-1638 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (39, 2, 10, 39, 'assembly_complete', 'Priya', datetime('now','-938 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (40, 2, 10, 40, 'assembly_complete', 'Hector', datetime('now','-740 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (41, 2, 11, 41, 'assembly_complete', 'Mateo', datetime('now','-1795 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (42, 2, 11, 44, 'to_assembly', 'Carlos', datetime('now','-95 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (43, 3, 12, 45, 'assembly_complete', 'Tony', datetime('now','-45 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (44, 3, 12, 46, 'assembly_complete', 'Marcus', datetime('now','-96 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (45, 3, 13, 49, 'to_assembly', 'Carlos', datetime('now','-13 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (46, 3, 13, 50, 'to_assembly', 'Carlos', datetime('now','-36 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (47, 3, 13, 51, 'to_assembly', 'Carlos', datetime('now','-36 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (48, 3, 13, 52, 'to_assembly', 'Carlos', datetime('now','-87 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (49, 3, 14, 53, 'to_assembly', 'Carlos', datetime('now','-90 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (50, 3, 14, 54, 'to_assembly', 'Carlos', datetime('now','-29 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (51, 3, 14, 55, 'to_assembly', 'Carlos', datetime('now','-44 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (52, 3, 14, 56, 'to_assembly', 'Carlos', datetime('now','-17 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (53, 3, 15, 57, 'to_assembly', 'Carlos', datetime('now','-40 minutes'));
INSERT INTO scans (id, job_id, bucket_id, cabinet_id, station, scanned_by, scanned_at) VALUES (54, 3, 15, 58, 'to_assembly', 'Carlos', datetime('now','-64 minutes'));

-- pause events (Lean reason signal)
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (1, 4, 7, 'missing_part', 'left side panel short', datetime('now','-654 minutes'), datetime('now','-652 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (2, 5, 8, 'break', NULL, datetime('now','-935 minutes'), datetime('now','-929 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (3, 6, 9, 'missing_part', 'left side panel short', datetime('now','-4069 minutes'), datetime('now','-4064 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (4, 7, 10, 'machine', NULL, datetime('now','-4143 minutes'), datetime('now','-4138 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (5, 8, 11, 'machine', NULL, datetime('now','-1551 minutes'), datetime('now','-1549 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (6, 8, 11, 'break', NULL, datetime('now','-1554 minutes'), datetime('now','-1549 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (7, 9, 4, 'break', NULL, datetime('now','-1562 minutes'), datetime('now','-1561 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (8, 9, 4, 'machine', NULL, datetime('now','-1568 minutes'), datetime('now','-1561 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (9, 10, 5, 'machine', NULL, datetime('now','-1687 minutes'), datetime('now','-1680 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (10, 11, 6, 'material_wait', NULL, datetime('now','-1728 minutes'), datetime('now','-1721 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (11, 13, 8, 'break', NULL, datetime('now','-2385 minutes'), datetime('now','-2383 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (12, 14, 9, 'missing_part', 'left side panel short', datetime('now','-1488 minutes'), datetime('now','-1484 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (13, 15, 10, 'break', NULL, datetime('now','-3111 minutes'), datetime('now','-3106 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (14, 16, 11, 'material_wait', NULL, datetime('now','-4300 minutes'), datetime('now','-4294 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (15, 16, 11, 'defect', NULL, datetime('now','-4297 minutes'), datetime('now','-4294 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (16, 19, 6, 'missing_part', 'left side panel short', datetime('now','-1937 minutes'), datetime('now','-1936 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (17, 20, 7, 'break', NULL, datetime('now','-3843 minutes'), datetime('now','-3839 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (18, 21, 8, 'material_wait', NULL, datetime('now','-4150 minutes'), datetime('now','-4145 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (19, 21, 8, 'break', NULL, datetime('now','-4149 minutes'), datetime('now','-4145 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (20, 22, 9, 'break', NULL, datetime('now','-3784 minutes'), datetime('now','-3783 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (21, 23, 10, 'help_needed', NULL, datetime('now','-2410 minutes'), datetime('now','-2406 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (22, 23, 10, 'missing_part', 'left side panel short', datetime('now','-2407 minutes'), datetime('now','-2406 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (23, 24, 11, 'defect', NULL, datetime('now','-442 minutes'), datetime('now','-438 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (24, 27, 6, 'help_needed', NULL, datetime('now','-447 minutes'), datetime('now','-440 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (25, 28, 7, 'missing_part', 'left side panel short', datetime('now','-446 minutes'), datetime('now','-443 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (26, 28, 7, 'material_wait', NULL, datetime('now','-447 minutes'), datetime('now','-443 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (27, 29, 8, 'machine', NULL, datetime('now','-419 minutes'), datetime('now','-415 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (28, 29, 8, 'material_wait', NULL, datetime('now','-422 minutes'), datetime('now','-415 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (29, 30, 9, 'material_wait', NULL, datetime('now','-354 minutes'), datetime('now','-347 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (30, 30, 9, 'defect', NULL, datetime('now','-353 minutes'), datetime('now','-347 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (31, 31, 10, 'material_wait', NULL, datetime('now','-116 minutes'), datetime('now','-113 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (32, 32, 11, 'help_needed', NULL, datetime('now','-233 minutes'), datetime('now','-231 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (33, 32, 11, 'defect', NULL, datetime('now','-234 minutes'), datetime('now','-231 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (34, 33, 4, 'defect', NULL, datetime('now','-43 minutes'), datetime('now','-39 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (35, 34, 5, 'help_needed', NULL, datetime('now','-98 minutes'), datetime('now','-95 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (36, 34, 5, 'defect', NULL, datetime('now','-100 minutes'), datetime('now','-95 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (37, 37, 8, 'material_wait', NULL, datetime('now','-991 minutes'), datetime('now','-987 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (38, 38, 9, 'defect', NULL, datetime('now','-1640 minutes'), datetime('now','-1639 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (39, 39, 10, 'missing_part', 'left side panel short', datetime('now','-942 minutes'), datetime('now','-939 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (40, 40, 11, 'machine', NULL, datetime('now','-747 minutes'), datetime('now','-741 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (41, 41, 4, 'defect', NULL, datetime('now','-1797 minutes'), datetime('now','-1796 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (42, 41, 4, 'defect', NULL, datetime('now','-1799 minutes'), datetime('now','-1796 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (43, 42, 5, 'material_wait', NULL, datetime('now','-12 minutes'), NULL);
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (44, 44, 7, 'material_wait', NULL, datetime('now','-51 minutes'), datetime('now','-46 minutes'));
INSERT INTO pause_events (id, build_session_id, user_id, reason, note, paused_at, resumed_at) VALUES (45, 47, 10, 'machine', NULL, datetime('now','-29 minutes'), NULL);

-- FixIt defects
INSERT INTO fixit_requests (id, cabinet_id, job_id, build_session_id, requested_by, root_cause, description, photo_key, status, resolved_by, resolved_at, resolution_note, created_at) VALUES (1, 28, 2, NULL, 4, 'cnc_error', 'Dado depth off by 1/8, shelf won''t seat', NULL, 'open', NULL, NULL, NULL, datetime('now','-58 minutes'));
INSERT INTO fixit_requests (id, cabinet_id, job_id, build_session_id, requested_by, root_cause, description, photo_key, status, resolved_by, resolved_at, resolution_note, created_at) VALUES (2, 39, 2, NULL, 6, 'material_defect', 'Veneer blowout on door face', NULL, 'open', NULL, NULL, NULL, datetime('now','-96 minutes'));
INSERT INTO fixit_requests (id, cabinet_id, job_id, build_session_id, requested_by, root_cause, description, photo_key, status, resolved_by, resolved_at, resolution_note, created_at) VALUES (3, 40, 2, NULL, 5, 'transit_damage', 'Corner crushed in transit from EB', NULL, 'resolved', 2, datetime('now','-4 minutes'), 'Re-cut on CNC, swapped in', datetime('now','-238 minutes'));
INSERT INTO fixit_requests (id, cabinet_id, job_id, build_session_id, requested_by, root_cause, description, photo_key, status, resolved_by, resolved_at, resolution_note, created_at) VALUES (4, 34, 2, NULL, 7, 'cnc_error', 'Hinge boring mislocated', NULL, 'resolved', 2, datetime('now','-6 minutes'), 'Re-cut on CNC, swapped in', datetime('now','-110 minutes'));
INSERT INTO fixit_requests (id, cabinet_id, job_id, build_session_id, requested_by, root_cause, description, photo_key, status, resolved_by, resolved_at, resolution_note, created_at) VALUES (5, 35, 2, NULL, 8, 'other', 'Missing 32mm shelf pins in nest', NULL, 'open', NULL, NULL, NULL, datetime('now','-116 minutes'));

-- remake flags
UPDATE cabinets SET flags = '["remake"]' WHERE id = 25;
UPDATE cabinets SET flags = '["remake"]' WHERE id = 26;
